sudo: required
services:
        - docker

before_install:
        - docker build -t changa2127/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run changa2127/react-test npm test -- --coverage 

after_success:
        - docker build -t changa2127/multi-client ./client 
        - docker build -t changa2127/multi-nginx ./nginx
        - docker build -t changa2127/multi-server ./server
        - docker build -t changa2127/multi-worker ./worker
        
        #Log in to Docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        #Take those images and push them to docker hub
        - docker push changa2127/multi-client
        - docker push changa2127/multi-nginx 
        - docker push changa2127/multi-server
        - docker push changa2127/multi-worker
deploy:
        provider: elasticbeanstalk
        region: ap-south-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-ap-south-1-567549317008        
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
